name = "pythagorean"
version = "0.1.0"
keywords = ["math", "theorem-proving", "inner-product-space"]
defaultTargets = ["Pythagorean", "pythagorean"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.34.0-rc2"

[[lean_lib]]
name = "Pythagorean"

[[lean_exe]]
name = "pythagorean"
root = "Main"
